create table pgxjob_jobs (
	id bigint primary key generated by default as identity,
	queue_name text not null,
	priority integer not null,
	type text not null,
	params jsonb,
	queued_at timestamptz not null,
	run_at timestamptz not null,
	locked_until timestamptz not null,
	error_count integer not null default 0,
	last_error text
);
