-- This file was generated by tern gengen v2.2.0-pre.
--
-- If using psql to execute this script use the --no-psqlrc, --tuples-only,
-- --quiet, and --no-align options to only output the migration SQL.
--
-- e.g. psql --no-psqlrc --tuples-only --quiet --no-align -f this_file.sql
--
-- The results can be redirected to a file where the proposed changes can be
-- inspected or the results can be piped back into psql to migrate immediately.
--
-- e.g. psql --no-psqlrc --tuples-only --quiet --no-align -f this_file.sql | psql

set tern.version = -1;
do $$
declare
	schema_version_table_exists boolean;
begin
	select to_regclass('pgxjob_version') is not null into schema_version_table_exists;
	if schema_version_table_exists then
		perform set_config('tern.version', version::text, false) from pgxjob_version;
	end if;
end
$$;

with migrations(version, up_sql) as (
	values
	(0,
$tern_gengen$
begin;
create table pgxjob_version(version int4 not null);
insert into pgxjob_version(version) values(0);
$tern_gengen$)

, (1,
$tern_gengen$
-- 001_pgxjob_setup.sql
begin;
create table pgxjob_queues (
	id int primary key generated by default as identity,
	name text not null unique
);

create table pgxjob_types (
	id int primary key generated by default as identity,
	name text not null unique
);

create table pgxjob_jobs (
	id bigint primary key generated by default as identity,
	queue_id int not null, -- purposely not a foreign key for best insert performance. pgxjob_queues rows are never deleted.
	priority integer not null,
	type_id int not null, -- purposely not a foreign key for best insert performance. pgxjob_types rows are never deleted.
	params json, -- use json instead of jsonb as it is faster for insert.
	queued_at timestamptz not null,
	run_at timestamptz not null,
	next_run_at timestamptz not null,
	error_count integer not null default 0,
	last_error text
);$tern_gengen$)

)
select up_sql || '
update pgxjob_version set version = ' || version || ';
commit;
'
from migrations
where version > current_setting('tern.version')::int4
order by version asc;

